server:
  port: 8080
  servlet:
    context-path: /  #项目要上下文的路径
#Spring的配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
      #jdbc:mysql://localhost:3306/bill-manager?useUnicode=true&character=utf-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/travel?useUnicode=true&character=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    #连接池的相关参数 不用配
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
  thymeleaf:
    cache: false
#mybatis的配置
mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.sx.entity
  configuration:
    lazy-loading-enabled: true  #打开懒加载
    aggressive-lazy-loading: false #关闭积极懒加载
